/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shine_controller_poker_ssz_tool_JniDemo */

#ifndef _Included_com_shine_controller_poker_ssz_tool_JniDemo
#define _Included_com_shine_controller_poker_ssz_tool_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shine_controller_poker_ssz_tool_JniDemo
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_shine_controller_poker_ssz_tool_JniDemo_set
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_shine_controller_poker_ssz_tool_JniDemo
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_shine_controller_poker_ssz_tool_JniDemo_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
